(function(){
    var modules={
        "panel-main-reshaped":    	        {url:"$H/m/panel-main.html",router:1},
        "panel-child-reshaped":              {url:"$H/m/panel-child.html"},
        "panel-library-reshaped":    		{url:"$H/m/panel-library.html",router:1},
        "panel-export-screening-reshaped":   {url:"$H/m/export/panel-export-screened.html",router:1},
        "panel-export-enrolled-reshaped":    {url:"$H/m/export/panel-export-enrolled.html",router:1},
        "export-data":		                {url:"$H/m/export/export-data.html",Table:"export-reshaped",form_module:"export-form"},
        "export-form":		                {url:"$H/m/export/export-form.html",Table:"export-reshaped"},
        
        "participant-data":   		        {url:"$H/m/participant/participant-data.html",Table:"participant-reshaped",form_module:"participant-form",router:1,
                                                child_panel:"panel-child-reshaped",
                                                questionnaire_setup:"online-questionnaire-setup-reshaped",
                                                online_questionnaire:"online-questionnaire-app-reshaped",
                                                participant_id:{field1:"Subject_ID",field2:"Subject_Initials"},
                                                participant_export:"ID,Subject_ID,Screening_Number,Randomisation_Number,Subject_Initials,Gender,DOB",
                                            },
       "participant-form":   		        {url:"$H/m/participant/participant-form.html",Table:"participant-reshaped"},

        "online-questionnaire-setup-reshaped": {url:"$H/m/oq-setup.html",Table:"participant-reshaped"},
        "online-questionnaire-app-reshaped":   {url:"$H/oq.html"},

        "notes-data":  	                    {url:"$H/m/library/notes-data.html",Table:"notes-reshaped",form_module:"notes-form",router:1},
        "notes-form":  	                    {url:"$H/m/library/notes-form.html",Table:"notes-reshaped"},

        "randomisation-table-data-reshaped":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-reshaped",form_module:"randomisation-table-form-reshaped"},
        "randomisation-table-form-reshaped":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-reshaped"},

        "file-notes-data-reshaped":		{url:"$H/m/library/file-notes-data.html",Table:"file-notes-reshaped",form_module:"file-notes-form-reshaped",task_name:"Unscheduled - File Notes"},
        "file-notes-form-reshaped":		{url:"$H/m/library/file-notes-form.html",Table:"file-notes-reshaped",task_name:"Unscheduled - File Notes"},
        "consent-ps-data-reshaped":		        {url:"$H/m/library/consent-data.html",Table:"consent-ps-reshaped",form_module:"consent-ps-form-reshaped",task_name:"Pre-screening - Consent"},
        "consent-ps-form-reshaped":		        {url:"$H/m/library/consent-form.html",Table:"consent-ps-reshaped",task_name:"Pre-screening - Consent"},
        "date-ps-data-reshaped":                {url:"$H/m/library/date-data.html",Table:"date-ps-reshaped",form_module:"date-ps-form-reshaped",task_name:"Pre-screening - Visit Date"},
        "date-ps-form-reshaped":                {url:"$H/m/library/date-form.html",Table:"date-ps-reshaped",task_name:"Screening - Visit Date"},
        "wristox-ps-data-reshaped":	    {url:"$H/m/library/wristox-data.html",Table:"wristox-ps-reshaped",form_module:"wristox-ps-form-reshaped",task_name:"Pre-screening - Wristox"},
        "wristox-ps-form-reshaped":	    {url:"$H/m/library/wristox-form.html",Table:"wristox-ps-reshaped",task_name:"Pre-screening - Wristox"},
        "mmse-ps-data-reshaped":	    {url:"$H/m/library/mmse-data.html",Table:"mmse-ps-reshaped",form_module:"mmse-ps-form-reshaped",task_name:"Pre-screening - MMSE"},
        "mmse-ps-form-reshaped":	    {url:"$H/m/library/mmse-form.html",Table:"mmse-ps-reshaped",task_name:"Pre-screening - MMSE"},
        "eligibility-ps-data-reshaped":	    {url:"$H/m/library/eligibility-ps-data.html",Table:"eligibility-ps-reshaped",form_module:"eligibility-ps-form-reshaped",task_name:"Pre-screening - Eligibility"},
        "eligibility-ps-form-reshaped":	    {url:"$H/m/library/eligibility-ps-form.html",Table:"eligibility-ps-reshaped",task_name:"Pre-screening - Eligibility"},

        "date-s-data-reshaped":                {url:"$H/m/library/date-data.html",Table:"date-s-reshaped",form_module:"date-s-form-reshaped",task_name:"Screening - Visit Date"},
        "date-s-form-reshaped":                {url:"$H/m/library/date-form.html",Table:"date-s-reshaped",task_name:"Screening - Visit Date"},
        "consent-s-data-reshaped":		        {url:"$H/m/library/consent-data.html",Table:"consent-s-reshaped",form_module:"consent-s-form-reshaped",task_name:"Screening - Consent"},
        "consent-s-form-reshaped":		        {url:"$H/m/library/consent-form.html",Table:"consent-s-reshaped",task_name:"Screening - Consent"},
        "mmse-s-data-reshaped":	            {url:"$H/m/library/mmse-data.html",Table:"mmse-s-reshaped",form_module:"mmse-s-form-reshaped",task_name:"Screening - MMSE"},
        "mmse-s-form-reshaped":	            {url:"$H/m/library/mmse-form.html",Table:"mmse-s-reshaped",task_name:"Screening - MMSE"},
        "demographics-s-data-reshaped":	            {url:"$H/m/library/demographics-data.html",Table:"demographics-s-reshaped",form_module:"demographics-s-form-reshaped",task_name:"Screening - Demographics"},
        "demographics-s-form-reshaped":	            {url:"$H/m/library/demographics-form.html",Table:"demographics-s-reshaped",task_name:"Screening - Demographics"},
        "medical-history-s-data-reshaped":	    {url:"$H/m/library/medical-history-data.html",Table:"medical-history-s-reshaped",form_module:"medical-history-s-form-reshaped",task_name:"Screening - Medical History Questionnaire"},
        "medical-history-s-form-reshaped":	    {url:"$H/m/library/medical-history-form.html",Table:"medical-history-s-reshaped",task_name:"Screening - Medical History Questionnaire"},
        "biomedical-measurements-s-data-reshaped":{url:"$H/m/library/biomedical-measurements-data.html",Table:"biomedical-measurements-s-reshaped",form_module:"biomedical-measurements-s-form-reshaped",task_name:"Screening - Biomedical Measurements"},
        "biomedical-measurements-s-form-reshaped":{url:"$H/m/library/biomedical-measurements-form.html",Table:"biomedical-measurements-s-reshaped",task_name:"Screening - Biomedical Measurements"},
        "in-ex-s-data-reshaped":	            {url:"$H/m/library/in-ex-data.html",Table:"in-ex-s-reshaped",form_module:"in-ex-s-form-reshaped",task_name:"Screening - Inclusion/ Exclusion Criteria"},
        "in-ex-s-form-reshaped":	            {url:"$H/m/library/in-ex-form.html",Table:"in-ex-s-reshaped",task_name:"Screening - Inclusion/ Exclusion Criteria"},

        "date-bl-data-reshaped":                {url:"$H/m/library/date-data.html",Table:"date-bl-reshaped",form_module:"date-bl-form-reshaped",task_name:"Baseline - Visit Date"},
        "date-bl-form-reshaped":                {url:"$H/m/library/date-form.html",Table:"date-bl-reshaped",task_name:"Baseline - Visit Date"},
        "watchpat-bl-data-reshaped":                {url:"$H/m/library/watchpat-data.html",Table:"watchpat-bl-reshaped",form_module:"watchpat-bl-form-reshaped",task_name:"Baseline - WatchPat"},
        "watchpat-bl-form-reshaped":                {url:"$H/m/library/watchpat-form.html",Table:"watchpat-bl-reshaped",task_name:"Baseline - WatchPat"},
        "medical-history-bl-data-reshaped":	    {url:"$H/m/library/medical-history-data.html",Table:"medical-history-bl-reshaped",form_module:"medical-history-bl-form-reshaped",task_name:"Baseline - Medical History Questionnaire"},
        "medical-history-bl-form-reshaped":	    {url:"$H/m/library/medical-history-form.html",Table:"medical-history-bl-reshaped",task_name:"Baseline - Medical History Questionnaire"},
        "demographics-bl-data-reshaped":                {url:"$H/m/library/demographics-data.html",Table:"demographics-bl-reshaped",form_module:"demographics-bl-form-reshaped",task_name:"Baseline - Demographics"},
        "demographics-bl-form-reshaped":                {url:"$H/m/library/demographics-form.html",Table:"demographics-bl-reshaped",task_name:"Baseline - Demographics"},
        "biomedical-measurements-bl-data-reshaped":                {url:"$H/m/library/biomedical-measurements-data.html",Table:"biomedical-measurements-bl-reshaped",form_module:"biomedical-measurements-bl-form-reshaped",task_name:"Baseline - Biomedical Measurements"},
        "biomedical-measurements-bl-form-reshaped":                {url:"$H/m/library/biomedical-measurements-form.html",Table:"biomedical-measurements-bl-reshaped",task_name:"Baseline - Biomedical Measurements"},
        "cirs-bl-data-reshaped":                {url:"$H/m/library/cirs-data.html",Table:"cirs-bl-reshaped",form_module:"cirs-bl-form-reshaped",task_name:"Baseline - Cumulative Illness Rating Scale"},
        "cirs-bl-form-reshaped":                {url:"$H/m/library/cirs-form.html",Table:"cirs-bl-reshaped",task_name:"Baseline - Cumulative Illness Rating Scale"},
        "ravlt-1-6-bl-data-reshaped":                {url:"$H/m/library/ravlt-1-6-data.html",Table:"ravlt-1-6-bl-reshaped",form_module:"ravlt-1-6-bl-form-reshaped",task_name:"Baseline - RAVLT Trials 1-6"},
        "ravlt-1-6-bl-form-reshaped":                {url:"$H/m/library/ravlt-1-6-form.html",Table:"ravlt-1-6-bl-reshaped",task_name:"Baseline - RAVLT Trials1-6"},
        "ravlt-7-bl-data-reshaped":                {url:"$H/m/library/ravlt-7-data.html",Table:"ravlt-7-bl-reshaped",form_module:"ravlt-7-bl-form-reshaped",task_name:"Baseline - RAVLT Trials 7"},
        "ravlt-7-bl-form-reshaped":                {url:"$H/m/library/ravlt-7-form.html",Table:"ravlt-7-bl-reshaped",task_name:"Baseline - RAVLT Trials 7"},
        "sdmt-bl-data-reshaped":                {url:"$H/m/library/sdmt-data.html",Table:"sdmt-bl-reshaped",form_module:"sdmt-bl-form-reshaped",task_name:"Baseline - Symbol Digit Modalities Test"},
        "sdmt-bl-form-reshaped":                {url:"$H/m/library/sdmt-form.html",Table:"sdmt-bl-reshaped",task_name:"Baseline - Symbol Digit Modalities Test"},
        "stroop-bl-data-reshaped":                {url:"$H/m/library/stroop-data.html",Table:"stroop-bl-reshaped",form_module:"stroop-bl-form-reshaped",task_name:"Baseline - DKEFS Stroop Test"},
        "stroop-bl-form-reshaped":                {url:"$H/m/library/stroop-form.html",Table:"stroop-bl-reshaped",task_name:"Baseline - DKEFS Stroop Test"},
        "palt-bl-data-reshaped":                {url:"$H/m/library/palt-data.html",Table:"palt-bl-reshaped",form_module:"palt-bl-form-reshaped",task_name:"Baseline - CANTAB Pair Associated Learning Test"},
        "palt-bl-form-reshaped":                {url:"$H/m/library/palt-form.html",Table:"palt-bl-reshaped",task_name:"Baseline - CANTAB Pair Associated Learning Test"},
        "rvpt-bl-data-reshaped":                {url:"$H/m/library/rvpt-data.html",Table:"rvpt-bl-reshaped",form_module:"rvpt-bl-form-reshaped",task_name:"Baseline - CANTAB Rapid Visual Processing Test"},
        "rvpt-bl-form-reshaped":                {url:"$H/m/library/rvpt-form.html",Table:"rvpt-bl-reshaped",task_name:"Baseline - CANTAB Rapid Visual Processing Test"},
        "multitasking-bl-data-reshaped":                {url:"$H/m/library/multitasking-data.html",Table:"multitasking-bl-reshaped",form_module:"multitasking-bl-form-reshaped",task_name:"Baseline - CANTAB Multitasking Test"},
        "multitasking-bl-form-reshaped":                {url:"$H/m/library/multitasking-form.html",Table:"multitasking-bl-reshaped",task_name:"Baseline - CANTAB Multitasking Test"},
        "bc-cci-bl-data-reshaped":                {url:"$H/m/library/bc-cci-data.html",Table:"bc-cci-bl-reshaped",form_module:"bc-cci-bl-form-reshaped",task_name:"Baseline - Brittish Colombia Cognitive Complaints Inventory"},
        "bc-cci-bl-form-reshaped":                {url:"$H/m/library/bc-cci-form.html",Table:"bc-cci-bl-reshaped",task_name:"Baseline - Brittish Colombia Cognitive Complaints Inventory"},
        "phq-9-bl-data-reshaped":                {url:"$H/m/library/phq-data.html",Table:"phq-9-bl-reshaped",form_module:"phq-9-bl-form-reshaped",task_name:"Baseline - The Patient Health Questionnaire-9 (PHQ-9)"},
        "phq-9-bl-form-reshaped":                {url:"$H/m/library/phq-form.html",Table:"phq-9-bl-reshaped",task_name:"Baseline - The Patient Health Questionnaire-9 (PHQ-9)"},
        "gad-7-bl-data-reshaped":                {url:"$H/m/library/gad7-data.html",Table:"gad-7-bl-reshaped",form_module:"gad-7-bl-form-reshaped",task_name:"Baseline - Generalised Anxiety Disorder – 7 (GAD-7)"},
        "gad-7-bl-form-reshaped":                {url:"$H/m/library/gad7-form.html",Table:"gad-7-bl-reshaped",task_name:"Baseline - Generalised Anxiety Disorder – 7 (GAD-7)"},
        "stop-bang-bl-data-reshaped":                {url:"$H/m/library/stop-bang-data.html",Table:"stop-bang-bl-reshaped",form_module:"stop-bang-bl-form-reshaped",task_name:"Baseline - STOP BANG"},
        "stop-bang-bl-form-reshaped":                {url:"$H/m/library/stop-bang-form.html",Table:"stop-bang-bl-reshaped",task_name:"Baseline - STOP BANG"},
        "pase-bl-data-reshaped":                {url:"$H/m/library/pase-data.html",Table:"pase-bl-reshaped",form_module:"pase-bl-form-reshaped",task_name:"Baseline - Physical Activity (PASE)"},
        "pase-bl-form-reshaped":                {url:"$H/m/library/pase-form.html",Table:"pase-bl-reshaped",task_name:"Baseline - Physical Activity (PASE)"},
        "eq-5d-bl-data-reshaped":                {url:"$H/m/library/eq-5d-data.html",Table:"eq-5d-bl-reshaped",form_module:"eq-5d-bl-form-reshaped",task_name:"Baseline - Australian Quality of life inventory (QOL-AD)"},
        "eq-5d-bl-form-reshaped":                {url:"$H/m/library/eq-5d-form.html",Table:"eq-5d-bl-reshaped",task_name:"Baseline - Australian Quality of life inventory (QOL-AD)"},
        "audit-bl-data-reshaped":                {url:"$H/m/library/audit-data.html",Table:"audit-bl-reshaped",form_module:"audit-bl-form-reshaped",task_name:"Baseline - Alcohol Use Disorders Identification Test (Audit)"},
        "audit-bl-form-reshaped":                {url:"$H/m/library/audit-form.html",Table:"audit-bl-reshaped",task_name:"Baseline - Alcohol Use Disorders Identification Test (Audit)"},
        "psqi-bl-data-reshaped":                {url:"$H/m/library/psqi-data.html",Table:"psqi-bl-reshaped",form_module:"psqi-bl-form-reshaped",task_name:"Baseline - The Pittsburgh Sleep Quality Index (PSQI)"},
        "psqi-bl-form-reshaped":                {url:"$H/m/library/psqi-form.html",Table:"psqi-bl-reshaped",task_name:"Baseline - The Pittsburgh Sleep Quality Index (PSQI)"},
        "ess-bl-data-reshaped":                {url:"$H/m/library/ess-data.html",Table:"ess-bl-reshaped",form_module:"ess-bl-form-reshaped",task_name:"Baseline - Epworth Sleepiness Scale (ESS)"},
        "ess-bl-form-reshaped":                {url:"$H/m/library/ess-form.html",Table:"ess-bl-reshaped",task_name:"Baseline - Epworth Sleepiness Scale (ESS)"},
        "isi-bl-data-reshaped":                {url:"$H/m/library/isi-data.html",Table:"isi-bl-reshaped",form_module:"isi-bl-form-reshaped",task_name:"Baseline - Insomia Severity Index (ISI)"},
        "isi-bl-form-reshaped":                {url:"$H/m/library/isi-form.html",Table:"isi-bl-reshaped",task_name:"Baseline - Insomia Severity Index (ISI)"},
        "btb-bl-data-reshaped":                {url:"$H/m/library/btb-data.html",Table:"btb-bl-reshaped",form_module:"btb-bl-form-reshaped",task_name:"Baseline - Blood Test Biomarkers"},
        "btb-bl-form-reshaped":                {url:"$H/m/library/btb-form.html",Table:"btb-bl-reshaped",task_name:"Baseline - Blood Test Biomarkers"},
        "mri-bl-data-reshaped":                {url:"$H/m/library/mri-data.html",Table:"mri-bl-reshaped",form_module:"mri-bl-form-reshaped",task_name:"Baseline - MRI data"},
        "mri-bl-form-reshaped":                {url:"$H/m/library/mri-form.html",Table:"mri-bl-reshaped",task_name:"Baseline - MRI data"},
        "pet-bl-data-reshaped":                {url:"$H/m/library/pet-data.html",Table:"pet-bl-reshaped",form_module:"pet-bl-form-reshaped",task_name:"Baseline - PET data"},
        "pet-bl-form-reshaped":                {url:"$H/m/library/pet-form.html",Table:"pet-bl-reshaped",task_name:"Baseline - PET data"},

    }
    for(p in modules){
        $vm.module_list[p]=modules[p];
        $vm.module_list[p].url=$vm.module_list[p].url.replace('$H',$vm.hosting_path);
    }
    //if(window.location.toString().indexOf('tb=demo')!=-1){
        for(p in $vm.module_list){
            $vm.module_list[p].Table="demo-"+$vm.module_list[p].Table;
            $vm.module_list[p].Table2="demo-"+$vm.module_list[p].Table2;
        }
    //}

})();
